      SUBROUTINE BIAS(N,XJ,XM,XMM,BIASM)
C Copyright, Bernd Berg, Jan 10 1992.
C ESTIMATES THE BIAS (ASSUMPTION: BIAS=CONST/N)  BIASM  AND
C THE BIAS-CORRECTED MEAN VALUE  XMM  FROM THE FOLLOWING 
C INPUT:  XJ(N) JACKKNIFE BINS AND  
C         XM    MEAN VALUE FROM ENTIRE STATISTICS.
C
      include 'implicit.sta'
      DIMENSION XJ(N)
      XJM=STMEAN(N,XJ)
      BIASM=(N-1)*(XM-XJM)
      XMM=XM+BIASM
      RETURN
      END 
