      PROGRAM BAUTO
C
C - INTEGRATED AUTOCORRELATION TIME BY BINNING:
C   TESTED FOR GAUSSIAN DATA GENERATED BY METROPOLIS MC.
C
      include '../../ForLib/implicit.sta'
      include '../../ForLib/constants.par'
      PARAMETER(IUO=6,IUD=10,ISEED1=1,ISEED2=0, K=17,NDAT=2**K)
      PARAMETER(KBMAX=K-12, A=THREE)
      DIMENSION DATA(NDAT),DATB(NDAT),DBE(0:K)
      COMMON /CHI2PAR/ NF         
C
      LTEST=.FALSE.
      LTEST=.TRUE.
C
      WRITE(IUO,*) ' '
      WRITE(IUO,*) 'NDAT,NBIN = ',NDAT,NBIN
C
      CALL RMASET(IUO,IUD,ISEED1,ISEED2,'ranmar.d')
      WRITE(IUO,*) 'Metropolis Range A = ',A
      CALL GAU_METRO(A,NDAT,DATA,XAM)
      WRITE(IUO,*) 'METROPOLIS FOR GAUSSIAN RANDOM NUMBERS: '
      WRITE(IUO,*) 'ACCEPTANCE RATE: ',XAM
C
      WRITE(IUO,*) '  '
      WRITE(IUO,'(" BININGS",9X,"MEAN",6X,"VARIANCE",5X,"ERROR BAR",
     &              9X,"RATIO")')
      OPEN(UNIT=IUD,FILE='b_aint.d',form='formatted',status='unknown') 
      DO KB=0,KBMAX
        NBIN=2**KB
        NBINS=NDAT/NBIN
        CALL BINING(NDAT,DATA,NBINS,DATB)
        CALL STEB0(NBINS,DATB, DBMEAN,DBV,DBE(KB))
        RATIO=(DBE(KB)/DBE(0))**2
        WRITE(IUO,'(1I7,4F14.6)') KB,DBMEAN,DBV,DBE(KB),RATIO
C 97.5% and 0.25\% confidence limits as substitute for two e-bar range. 
        NF=NBINS-1
        RAT_U=ZERO
        RAT_D=ZERO
        RAT_U=RATIO/chi2pdf_xq(P025)
        RAT_D=RATIO/chi2pdf_xq(P975)
        RAT_E=(RAT_U-RAT_D)/FOUR
c       XBIN=NBIN*ONE-ONE/FOUR
        XBIN=ONE*(NBIN-1)
        WRITE(IUD,'(I4,F8.2,I10,5F9.5)')
     &    KB,XBIN,NBINS,RATIO,RAT_E,(100*DBE(KB)**2),RAT_U,RAT_D
      END DO
      CLOSE(IUD)
      IF(LTEST) STOP 'LTEST.'
C
      WRITE(IUO,*) '  '
      OPEN(UNIT=IUD,FILE='b2_aint.d',form='formatted',status='unknown') 
      NDA2=NDAT/2
      DO IDAT=1,NDA2
        DATA(IDAT)=DATA(2*IDAT-1)
      END DO
      DO KB=0,KBMAX
        NBIN=2**KB
        NBINS=NDA2/NBIN
        CALL BINING(NDA2,DATA,NBINS,DATB)
        CALL STEB0(NBINS,DATB, DBMEAN,DBV,DBE(KB))
        RATIO=(DBE(KB)/DBE(0))**2
        WRITE(IUO,'(1I7,4F14.6)') KB,DBMEAN,DBV,DBE(KB),RATIO
C 97.5% and 0.25\% confidence limits as substitute for two e-bar range. 
        NF=NBINS-1
        RAT_U=RATIO/chi2pdf_xq(P025)
        RAT_D=RATIO/chi2pdf_xq(P975)
        RAT_E=(RAT_U-RAT_D)/FOUR
        WRITE(IUD,'(2I4,I10,4F10.5)') 
     &    KB,NBIN,NBINS,RATIO,RAT_E,RAT_U,RAT_D
      END DO
      CLOSE(IUD)
C
      STOP
      END

      INCLUDE '../../ForLib/bining.f'
      INCLUDE '../../ForLib/gau_metro.f'
      INCLUDE '../../ForLib/ranmar.f'
      INCLUDE '../../ForLib/rmaset.f'
      INCLUDE '../../ForLib/steb0.f'

      include '../../ForLib/chi2pdf_xq.f'
      include '../../ForLib/chi2_xq.f'
      include '../../ForLib/chi2_df.f'
      include '../../ForLib/fi1.f'
      include '../../ForLib/gamma_ln.f'
      include '../../ForLib/gamma_p.f'
