      PROGRAM AUTO_G17
C
C Copyright, Bernd Berg, Feb 11, 2001.
C - AUTOCORRELATION FUNCTIN AND INTEGRATED AUTOCORRELATION TIME: 
C   TESTED FOR GAUSSIAN DATA GENERATED BY METROPOLIS MC.
C
      include '../../ForLib/implicit.sta'
      include '../../ForLib/constants.par'
      PARAMETER(IUO=6,IUD=10,IUD1=11,ISEED1=1,ISEED2=0)
      PARAMETER(K=17,NDAT=2**K,NBINS=32,LMEAN=.FALSE.,A=THREE,NT=32)
      DIMENSION DATA(NDAT),ACORJ(NBINS,0:NT),ACOR(0:NT)
      DIMENSION ACINTJ(NBINS,0:NT),ACINT(0:NT),WORK(NBINS)
C
      LTEST=.false.
      LTEST=.true.
C
      WRITE(IUO,*) ' '
      WRITE(IUO,*) 'NDAT  =  ',NDAT
      WRITE(IUO,*) 'NBINS =  ',NBINS
      WRITE(IUO,*) 'RANGE A = ',A
C
C Generation of Gaussian Metropolis data:
C
      CALL RMASET(IUO,IUD,ISEED1,ISEED2,'ranmar.d')
      CALL GAU_METRO(A,NDAT,DATA,XAM)
      WRITE(IUO,*) 'METROPOLIS FOR GAUSSIAN RANDOM NUMBERS: '
      WRITE(IUO,*) 'ACCEPTANCE RATE: ',XAM
      CALL STEB0(NDAT,DATA,DM,DV,DE)
      WRITE(IUO,*) "DM,DV,DE:",DM,DV,DE
C
      OPEN(IUD,FILE='acor.d',FORM='formatted',STATUS='unknown')
      OPEN(IUD1,FILE='acor.small',FORM='formatted',STATUS='unknown')
      WRITE(IUO,*) ' '
      DO IT=0,NT
        ACOR(IT)=AUTCORF(IT,NDAT,DATA,LMEAN)
        CALL AUTCORJ(IT,NDAT,NBINS,DATA,WORK,ACORJ(1,IT),LMEAN)
        CALL STEBJ0(NBINS,ACORJ(1,IT),ACM,ACV,ACE)
        WRITE(IUO,'(" IT,ACOR:",1I6,2F15.9," +/-",1F15.9)') 
     &                IT,ACOR(IT),ACM,ACE
        ABIAS=100*ABS(ACOR(IT)-ACM)/ABS(ACOR(IT)) ! Bias in %.
        WRITE(IUD,'(1I6,3F14.8,1F14.4)') IT,ACOR(IT),ACM,ACE,ABIAS
        ACM_s=FIVE/TEN+50*ACM
        ACE_s=50*ACE 
        IF(IT>=11) WRITE(IUD1,'(1I6,2F14.8)') IT,ACM_s,ACE_s
      END DO
      CLOSE(IUD)
      CLOSE(IUD1)
      IF(LTEST) STOP "AUTO_G01: LTEST."
C
      OPEN(IUD,FILE='at_int.d',FORM='formatted',STATUS='unknown')
      CALL AC_INT(NT,ACOR,ACINT)
      CALL AC_INTJ(NT,NBINS,ACORJ,ACINTJ)
      WRITE(IUO,*) "  "
      DO IT=0,NT
        CALL STEBJ0(NBINS,ACINTJ(1,IT),ACM,ACV,ACE)
        WRITE(IUO,'(" IT,ACINT:",1I6,2F15.9," +/-",1F15.9)') 
     &                IT,ACINT(IT),ACM,ACE
        ABIAS=100*ABS(ACINT(IT)-ACM)/ACINT(IT) ! Bias in %.
        WRITE(IUD,'(1I6,3F14.8,1F14.4)') IT,ACINT(IT),ACM,ACE,ABIAS
      END DO
      CLOSE(IUD)
C
      STOP
      END

      INCLUDE '../../ForLib/ac_int.f'
      INCLUDE '../../ForLib/ac_intj.f'
      INCLUDE '../../ForLib/autcorf.f'
      INCLUDE '../../ForLib/autcorj.f'
      INCLUDE '../../ForLib/bias.f'
      INCLUDE '../../ForLib/bining.f'
      INCLUDE '../../ForLib/datjack.f'
      INCLUDE '../../ForLib/gau_metro.f'
      INCLUDE '../../ForLib/ranmar.f'
      INCLUDE '../../ForLib/rmaset.f'
      INCLUDE '../../ForLib/steb0.f'
      INCLUDE '../../ForLib/stebj0.f'
      INCLUDE '../../ForLib/stmean.f'
