      PROGRAM AT128_14
C
C Copyright, Bernd Berg, Feb 21 2001.
C - AUTOCORRELATION FUNCTIN AND INTEGRATED AUTOCORRELATION TIME: 
C   TESTED FOR GAUSSIAN DATA GENERATED BY METROPOLIS MC.
C
      include '../../ForLib/implicit.sta'
      include '../../ForLib/constants.par'
      PARAMETER(IUO=6,IUD=10,ISEED1=1,ISEED2=0, NRPT=128)
      PARAMETER(K=14,NDAT=2**K,NBINS=32,LMEAN=.FALSE.,A=THREE,NT=15)
      DIMENSION DATA(NDAT),ACORJ(NBINS,0:NT),ACOR(0:NT),WORK(NBINS)
      DIMENSION ACINTJ(NBINS,0:NT),ACINT(0:NT),ACE(0:NT),ATAU(NRPT,0:NT)
C
      LTEST=.true.
      LTEST=.false.
C
      WRITE(IUO,*) ' '
      WRITE(IUO,*) 'NRPT  =  ',NRPT
      WRITE(IUO,*) 'NDAT  =  ',NDAT
      WRITE(IUO,*) 'NBINS =  ',NBINS
      WRITE(IUO,*) 'RANGE A = ',A
C
C Generation of Gaussian Metropolis data:
C
      CALL RMASET(IUO,IUD,ISEED1,ISEED2,'ranmar.d')
      DO IRPT=1,NRPT
        CALL GAU_METRO(A,NDAT,DATA,XAM)
C
        DO IT=0,NT
          ACOR(IT)=AUTCORF(IT,NDAT,DATA,LMEAN)
          CALL AUTCORJ(IT,NDAT,NBINS,DATA,WORK,ACORJ(1,IT),LMEAN)
          CALL STEBJ0(NBINS,ACORJ(1,IT),ACM,ACV,ACE(IT))
        END DO
C
        CALL AC_INT(NT,ACOR,ACINT)
        CALL AC_INTJ(NT,NBINS,ACORJ,ACINTJ)
        DO IT=0,NT
          CALL STEBJ0(NBINS,ACINTJ(1,IT),ACM,ACV,ACE(IT))
          ABIAS=100*ABS(ACINT(IT)-ACM)/ACINT(IT) ! Bias in %.
          ATAU(IRPT,IT)=ACINT(IT) ! The less biased estimator.
          IF(LTEST) WRITE(IUO,'(1I6,2F14.8)') IT,ACINT(IT),ACE(IT)
        END DO
        IF(LTEST) STOP "AUTO_GAU: LTEST."
C
      END DO
C
      WRITE(IUO,*) " "
      WRITE(IUO,*) "Final: "
      DO IT=0,NT
        CALL STEB0(NRPT,ATAU(1,IT),ACINT(IT),ACV,ACE(IT))
        WRITE(IUO,'(1I6,2F14.8)') IT,ACINT(IT),ACE(IT)
      END DO
C
      STOP
      END

      INCLUDE '../../ForLib/ac_int.f'
      INCLUDE '../../ForLib/ac_intj.f'
      INCLUDE '../../ForLib/autcorf.f'
      INCLUDE '../../ForLib/autcorj.f'
      INCLUDE '../../ForLib/bias.f'
      INCLUDE '../../ForLib/bining.f'
      INCLUDE '../../ForLib/datjack.f'
      INCLUDE '../../ForLib/gau_metro.f'
      INCLUDE '../../ForLib/ranmar.f'
      INCLUDE '../../ForLib/rmaset.f'
      INCLUDE '../../ForLib/steb0.f'
      INCLUDE '../../ForLib/stebj0.f'
      INCLUDE '../../ForLib/stmean.f'
